apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ .Values.global.namespaces.backend }}
  labels:
    app: auth-service
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        environment: {{ .Values.global.environment }}
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.global.imageRegistry }}/auth-service:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
          envFrom:
            - configMapRef:
                name: auth-config
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu:    {{ .Values.global.resources.requests.cpu | quote }}
              memory: {{ .Values.global.resources.requests.memory | quote }}
            limits:
              cpu:    {{ .Values.global.resources.limits.cpu | quote }}
              memory: {{ .Values.global.resources.limits.memory | quote }}
