apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: auth-service-netpol
  namespace: {{ .Values.global.namespaces.backend }}
spec:
  podSelector:
    matchLabels:
      app: auth-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from gateway namespace
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.namespaces.gateway }}
      ports:
        - port: {{ .Values.port }}
    # Allow from frontend namespace
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.namespaces.frontend }}
      ports:
        - port: {{ .Values.port }}
    # Allow from order-service (same namespace, for token validation)
    - from:
        - podSelector:
            matchLabels:
              app: order-service
      ports:
        - port: {{ .Values.port }}
  egress:
    # Allow to mongodb-auth only
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.namespaces.database }}
          podSelector:
            matchLabels:
              app: mongodb-auth
      ports:
        - port: 27017
    # Allow DNS
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
