apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.global.namespaces.backend }}
  labels:
    app: auth-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: auth-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
