apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  namespace: {{ .Values.global.namespaces.backend }}
  labels:
    app: product-service
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  MONGO_URI: {{ printf "mongodb://%s:%s@mongodb-product-0.mongodb-product-headless.%s.svc.cluster.local:27017/%s" .Values.global.mongodb.username .Values.global.mongodb.password .Values.global.namespaces.database .Values.env.MONGO_DB_NAME | b64enc | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | b64enc | quote }}
