apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Values.global.namespaces.backend }}
  labels:
    app: product-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: product-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: product-service-netpol
  namespace: {{ .Values.global.namespaces.backend }}
spec:
  podSelector:
    matchLabels:
      app: product-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.namespaces.gateway }}
      ports:
        - port: {{ .Values.port }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.namespaces.frontend }}
      ports:
        - port: {{ .Values.port }}
    - from:
        - podSelector:
            matchLabels:
              app: order-service
      ports:
        - port: {{ .Values.port }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.namespaces.database }}
          podSelector:
            matchLabels:
              app: mongodb-product
      ports:
        - port: 27017
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
