apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.global.namespaces.frontend }}
  labels:
    app: frontend
    environment: {{ .Values.global.environment }}
data:
  REACT_APP_AUTH_URL:    {{ .Values.env.REACT_APP_AUTH_URL | quote }}
  REACT_APP_PRODUCT_URL: {{ .Values.env.REACT_APP_PRODUCT_URL | quote }}
  REACT_APP_ORDER_URL:   {{ .Values.env.REACT_APP_ORDER_URL | quote }}
