apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: {{ .Values.global.namespaces.backend }}
  labels:
    app: order-service
    environment: {{ .Values.global.environment }}
data:
  MONGO_DB_NAME:       {{ .Values.env.MONGO_DB_NAME | quote }}
  AUTH_SERVICE_URL:    {{ .Values.env.AUTH_SERVICE_URL | quote }}
  PRODUCT_SERVICE_URL: {{ .Values.env.PRODUCT_SERVICE_URL | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: {{ .Values.global.namespaces.backend }}
  labels:
    app: order-service
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  MONGO_URI:  {{ printf "mongodb://%s:%s@mongodb-order-0.mongodb-order-headless.%s.svc.cluster.local:27017/%s" .Values.global.mongodb.username .Values.global.mongodb.password .Values.global.namespaces.database .Values.env.MONGO_DB_NAME | b64enc | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | b64enc | quote }}
