replicaCount: 1

image:
  tag: "latest"
  pullPolicy: IfNotPresent

port: 8000

service:
  type: ClusterIP
  port: 8000

env:
  MONGO_DB_NAME:       "orderdb"
  AUTH_SERVICE_URL:    "http://auth-service.backend.svc.cluster.local:3001"
  PRODUCT_SERVICE_URL: "http://product-service.backend.svc.cluster.local:3002"
